### ISSUE TITLE
Correct wavelengths for JWST velocity

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#1742]
The JCCWG has requested the addition of wavelength corrections for the effective velocity of JWST relative to the barycenter for any given exposure. There are 3 components to implementing this:

- [x] Add the keyword VELOSYS to the wcsinfo schema (corresponding KWD ticket is https://jira.stsci.edu/browse/JWSTKD-193) [#2406]
- [x] Update one of the pointing/velocity/time scripts applied during level-1b processing to compute the appropriate value for VELOSYS and populate it [#2359]
- [x] Update the assign_wcs step to compute the wavelength correction and add it as another transform in the WCS object for spectroscopic exposures [#2406]

**Comment by hbushouse** [comment]
[CALWG_doppler_lambda_correction.pdf](https://github.com/STScI-JWST/jwst/files/1721876/CALWG_doppler_lambda_correction.pdf)

**Comment by hbushouse** [comment]
https://jira.stsci.edu/browse/JP-245

**Comment by nden** [comment]
For EXPTYPE `NRS_FIXEDSLIT` and `NRS_MSASPEC` the extract_2d step computes a wavelength zero-point correction and applies it to the computed wavelengths. The zero-point correction also needs to be corrected for the JWST velocity.

**Comment by hbushouse** [comment]
This is a high priority enhancement for B7.2, in order to produce properly calibrated data products.

**Comment by stscicrawford** [comment]
Also related: https://jira.stsci.edu/browse/JP-244

**Comment by philhodge** [comment]
Here are a few comments/questions.
VELOSYS is a FITS keyword for spectral coordinates, so it belongs in an extension header.  I suppose that would be the SCI header for level 1b data, but should VELOSYS also be added to the `MultiSpecModel` and the `SlitDataModel`?
If the INT_TIMES table is populated, the change in (UTC - TDB) from one integration to the next will be proportional to the radial velocity.  Even if there's just one integration, it should be easy to modify the `utc_to_bary` module (for populating the TDB columns in the INT_TIMES table) to have it also compute the radial velocity.
Should there be a header keyword that indicates that the wavelengths have been corrected for radial velocity?  Or can we assume that if S_WCS is 'COMPLETE' that the wavelengths will have been corrected?
This is to be a barycentric velocity correction rather than heliocentric?  I don't think the difference will be detectable, but we do have to call it something, and @hbushouse  did say "relative to the barycenter."

**Comment by hbushouse** [comment]
WFSS and TSGRISM modes implemented in #2801.
