### ISSUE TITLE
Step.save_results does not update meta.filename properly

### ISSUE THREAD

**Issue by stscijgbot** [spacetelescope/jwst#4138]
Issue [JP-1057](https://jira.stsci.edu/browse/JP-1057) was created by James Davies:

Before the merging of 

https://github.com/spacetelescope/jwst/pull/4090

into `master`, there was a bug in how `ModelContainer` was written out at the end of a `Step` when `save_results=True`.  Before it would just overwrite the input unless one specifically renamed the files in `meta.filename` within the step.  Not good.  And our master background unit tests masked this.

After the merge of #4090, this no longer happens.  Each member of a `ModelContainer` resulting from a step has its suffix replaced in the standard way, and we no longer get the inputs overwritten.  Good!

So we need to understand why this is, update the masterbackground regression tests, and see how this might be related to #4097.

**Comment by stscijgbot** [comment]
Comment by James Davies: The test failures we are seeing:

https://plwishmaster.stsci.edu:8081/job/RT/job/JWST/411/testReport/jwst.tests_nightly.general.miri.test_miri_steps_single/


- [ ] jwst.tests_nightly.general.miri.test_miri_steps_single.TestMIRIMasterBackgroundLRSDedicated.test_miri_masterbg_lrs_dedicated
- [ ] jwst.tests_nightly.general.miri.test_miri_steps_single.TestMIRIMasterBackgroundLRSNodded.test_miri_masterbg_lrs_nodded
- [ ] jwst.tests_nightly.general.miri.test_miri_steps_single.TestMIRIMasterBackgroundMRSDedicated.test_miri_masterbg_mrs_dedicated
- [ ] jwst.tests_nightly.general.miri.test_miri_steps_single.TestMIRIMasterBackgroundMRSNodded.test_miri_masterbg_mrs_nodded

**Comment by stscijgbot** [comment]
Comment by James Davies: The test failures we are seeing:

https://plwishmaster.stsci.edu:8081/job/RT/job/JWST/411/testReport/jwst.tests_nightly.general.miri.test_miri_steps_single/

- [ ] test_miri_masterbg_lrs_dedicated
- [ ] test_miri_masterbg_lrs_nodded
- [ ] test_miri_masterbg_mrs_dedicated
- [ ] test_miri_masterbg_mrs_nodded
