### ISSUE TITLE
move various telescope information scripts into main tree

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#470]
# Implementation

## Scripts to move:
- [ ] set_bary_helio_times.py
- [x] set_telescope_pointing.py _resolved by #1071_
- [ ] set_velocity_aberration.py

## ToDo
- [ ] Name of package?

**Comment by melanieclarke** [comment]
set_bary_helio_times was moved to SDP code, set_velocity_aberration is supported in jwst/scripts.
